name: comp0197-cw2-pt
channels:
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
  - conda-forge
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/pytorch/
  - defaults
dependencies:
  - python=3.10
  - numpy=2.2.4
  - pandas=2.2.3
  - pip=25.0
  - setuptools=75.8.0
  - wheel=0.45.1
  - ncurses
  - xz
  - zlib
  - bzip2
  - libffi
  - libuuid
  - readline
  - openssl
  - tk
  - sqlite
  - libopenblas
  - libblas
  - libcblas
  - liblapack
  - libgfortran
  - libgfortran5
  - expat
  - libexpat
  - ca-certificates
  - pip:
      - git+https://github.com/lucasb-eyer/pydensecrf.git
      - filelock==3.18.0
      - fsspec==2025.3.2
      - jinja2==3.1.6
      - markupsafe==3.0.2
      - mpmath==1.3.0
      - networkx==3.4.2
      - opencv-python==4.11.0.86
      - pillow==11.1.0
      - python-dateutil==2.9.0.post0
      - pytz==2025.2
      - six==1.17.0
      - sympy==1.13.1
      - torch==2.5.0
      - torchvision==0.20.0
      - tqdm==4.67.1
      - typing-extensions==4.13.2
      - tzdata==2025.2